export enum APIErrorCode {
    // GENERAL
    UNKNOWN = 1,
    UNKNOWN_METHOD = 10,
    APPLICATION_REQUEST_LIMIT_REACHED = 11,
    USER_PERFORMING_TOO_MANY_ACTIONS = 12,
    SYSTEM_TEMPORARILY_UNAVAILABLE = 20,
    INVALID_IP_ADDRESS = 21,
    INVALID_REQUEST = 22,

    // OAUTH 1.0
    MISSING_OAUTH_PARAMETERS = 2,
    UNSUPPORTED_OAUTH_PARAMETER = 3,
    INVALID_SIGNATURE_METHOD = 4,
    INVALID_CONSUMER_KEY = 5,
    INVALID_EXPIRED_TIMESTAMP = 6,
    INVALID_USED_NONCE = 7,
    INVALID_SIGNATURE = 8,
    INVALID_ACCESS_TOKEN = 9,

    // OAUTH 2.0
    INVALID_TOKEN = 13,
    MISSING_SCOPE = 14,

    // PARAMETER ERRORS
    MISSING_REQUIRED_PARAMETER = 101,
    INVALID_INTEGER_VALUE = 102,
    INVALID_DOUBLE_VALUE = 103,
    INVALID_DECIMAL_VALUE = 104,
    INVALID_LONG_VALUE = 105,
    INVALID_ID = 106,
    VALUE_OUT_OF_RANGE = 107,
    INVALID_TYPE = 108,

    // APPLICATION ERRORS
    ACTIVITY_NOT_FOUND = 201,
    SHIFT_TO_AND_SHIFT_FROM_MUST_BE_DIFFERENT = 202,
    TOO_MANY_MINUTES = 203,
    DATE_SELECTED_DOES_NOT_HAVE_AN_ACTIVITY = 204,
    DATE_MUST_BE_WITHIN_2_DAYS = 205,
    CANNOT_UPDATE_WEIGHT_FOR_EARLIER_DATE = 206,
    DATE_SELECTED_DOES_NOT_HAVE_ANY_FOOD_ENTRIES_TO_COPY = 207,
    INVALID_REGION = 208,
    ACTIVITY_CANNOT_BE_MODIFIED = 209,
    USER_CANNOT_HAVE_TEMPLATES_SET = 210
}

// TODO: Remove since api now throw proper error codes
export class APIError extends Error {
    public readonly code: APIErrorCode;

    constructor(code: APIErrorCode, message?: string) {
        super(message);

        this.name = "FatSecretError";
        this.code = code;
    }
}